# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Expo Build APK CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        android-version: [21]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Java JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: "oracle"
        java-version: 11
        
    - name: Use Android Manager
      uses: android-actions/setup-android@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 🏗 Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install Node dependencies
      run: npm ci
      
    - name: Install Android SDK and platform tools
      run: sdkmanager "platform-tools" "platforms;android-${{ matrix.android-version }}"
    
    - name: Create APK with EAS
      run: eas build -p android --profile preview --local -o builds/preview.apk
    
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/builds/preview.apk
    
